export default [
  {
    id: 1,
    name: "Max",
    surname: "Planck",
    registrationDate: "Fri Oct 29 2021",
    isActive: true,
    accounts: [
      {
        id: 1,
        type: "debit",
        creationDate: "Fri Oct 29 2021",
        expirationDate: "Tue Oct 29 2024",
        currency: "UAH",
        isActive: true,
        balance: 1000,
      },
      {
        id: 2,
        type: "credit",
        creationDate: "Fri Oct 29 2021",
        expirationDate: "Tue Oct 29 2024",
        currency: "EUR",
        isActive: true,
        balance: 500,
        creditLimit: 1000,
        personalFunds: 0,
        usedCreditFunds: 500,
      },
    ],
  },
  {
    id: 2,
    name: "Bob",
    surname: "Marvel",
    registrationDate: "Fri Oct 29 2021",
    isActive: false,
    accounts: [
      {
        id: 3,
        type: "debit",
        creationDate: "Fri Oct 29 2021",
        expirationDate: "Tue Oct 29 2024",
        currency: "USD",
        isActive: true,
        balance: 2000,
      },
      {
        id: 4,
        type: "credit",
        creationDate: "Fri Oct 29 2021",
        expirationDate: "Tue Oct 29 2024",
        currency: "USD",
        isActive: true,
        balance: 1000,
        creditLimit: 3000,
        personalFunds: 0,
        usedCreditFunds: 2000,
      },
    ],
  },
  {
    id: 3,
    name: "Ben",
    surname: "Polyak",
    registrationDate: "Fri Oct 29 2021",
    isActive: true,
    accounts: [],
  },
 
];
